### ISSUE TITLE
MissingMethodException when use Deploy-Graph-Documentation  task

### ISSUE THREAD

**Issue by vCipher** [cake-contrib/Cake.Recipe#178]
When I try to start Deploy-Graph-Documentation task, I get such exception:
```
Error: 
System.AggregateException: One or more errors occurred. ---> System.MissingMethodException: Method not found: 'System.Collections.Generic.IReadOnlyList`1<System.String> Cake.Core.CakeTask.get_Dependencies()'.
   at Cake.Graph.GraphRunner.GetTaskGraphNodes
(CakeTask task)
   at Cake.Graph.GraphRunner.CreateNodeSetFile(CakeTask task, GraphSettings settings)
   at Cake.Graph.GraphRunner.GenerateNodeSets(GraphSettings settings)
   at Submission#0.<<Initialize>>b__0_120()
   at Cake.Core.CakeTaskBuilderExtensions.<>c__DisplayClass8_0.<Does>b__0(ICakeContext x)
   at Cake.Core.ActionTask.<Execute>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Core.DefaultExecutionStrategy.<ExecuteAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Core.CakeEngine.<ExecuteTaskAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Core.CakeEngine.<RunTargetAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Scripting.BuildScriptHost.<RunTargetAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Core.Scripting.ScriptHost.RunTarget(String target)
   at Submission#0.<get_Build>b__503_0(String target)
   at Submission#0.Builder.Run()

```
More build log [here](https://ci.appveyor.com/project/cakecontrib/cake-hg/build/0.2.0-alpha.14.build.29)

**Comment by vCipher** [comment]
I have investigated this issue and found that Cake.Graph uses `<package id="Cake" version="0.21.1" />` and I use  `<package id="Cake" version="0.23.0" />`. This version difference produces sutiation, in witch Cake.Core, Version=0.23.0.0 exports member ```{System.Collections.Generic.IReadOnlyList`1[Cake.Core.CakeTaskDependency] get_Dependencies()}```

![image](https://user-images.githubusercontent.com/5900205/32757114-77da7430-c929-11e7-9dfb-0442379f5187.png)

And Cake.Graph, Version=0.1.0.0 requires  ```System.Collections.Generic.IReadOnlyList`1<System.String> Cake.Core.CakeTask.get_Dependencies()```

**Comment by gep13** [comment]
@vCipher I believe the latest version of Cake.Graph should now support the latest version of Cake.
