### ISSUE TITLE
DotNetCore-Test fails due to incorrect path for test project

### ISSUE THREAD

**Issue by tjackadams** [cake-contrib/Cake.Recipe#193]
### Problem
The following error message is displayed when running "DotNetCore-Test"

```
Cake.exe : The test source file "C:\projects\portal\test\Portal.Tests\bin\Any CPU\Release\netcoreapp2.0\Portal.Tests.dll" provided was not found.
At line:1 char:1
+ & "C:\projects\portal\tools\Cake\Cake.exe" "setup.cake" -target="AppV ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (The test source... was not found.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```

The command i am using is `.\build.ps1 -Target AppVeyor -Verbosity Diagnostic` and the build only fails when running on AppVeyor.

I think i know the problem is because its inserting "Any CPU" into the path, but i have no idea why it would only do this on AppVeyor, locally it runs fine and uses the correct path.

It looks like it happens when passing it across to OpenCover.

Here is the error at the bottom of the output

```
Error: 
System.AggregateException: One or more errors occurred. ---> Cake.Core.CakeException: OpenCover: Process returned an error (exit code 1).
   at Cake.Core.Tooling.Tool`1.ProcessExitCode(Int32 exitCode) in C:\projects\cake\src\Cake.Core\Tooling\Tool.cs:line
 139
   at Cake.Core.Tooling.Tool`1.Run(TSettings settings, ProcessArgumentBuilder arguments, ProcessSettings processSettings, Action`1 postAction) in C:\projects\cake\src\Cake.Core\Tooling\Tool.cs:line 119
   at Cake.Common.Tools.OpenCover.OpenCoverRunner.Run(ICakeContext context, Action`1 action, FilePath outputPath, OpenCoverSettings settings) in C:\projects\cake\src\Cake.Common\Tools\OpenCover\OpenCoverRunner.cs:line 72
   at Cake.Common.Tools.OpenCover.OpenCoverAliases.OpenCover(ICakeContext context, Action`1 action, FilePath outputFile, OpenCoverSettings settings) in C:\projects\cake\src\Cake.Common\Tools\OpenCover\OpenCoverAliases.cs:line 66
   at Submission#0.OpenCover(Action`1 action, FilePath outputFile, OpenCoverSettings settings)
   at Submission#0.<<Initialize>>b__0_81()
   at Cake.Core.CakeTaskBuilderExtensions.<>c__DisplayClass8_0.<Does>b__0(ICakeContext x) in C:\projects\cake\src\Cake.Core\CakeTaskBuilderExtensions.cs:line 185
   at Cake.Core.ActionTask.<Execute>d__14.MoveNext() in C:\projects\cake\src\Cake.Core\ActionTask.cs:line 100
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Core.DefaultExecutionStrategy.<ExecuteAsync>d__4.MoveNext() in C:\projects\cake\src\Cake.Core\DefaultExecutionStrategy.cs:line 87
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Core.CakeEngine.<ExecuteTaskAsync>d__29.MoveNext() in C:\projects\cake\src\Cake.Core\CakeEngine.cs:line 266
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Core.CakeEngine.<RunTargetAsync>d__18.MoveNext() in C:\projects\cake\src\Cake.Core\CakeEngine.cs:line 164
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Scripting.BuildScriptHost.<RunTargetAsync>d__3.MoveNext() in C:\projects\cake\src\Cake\Scripting\BuildScriptHost.cs:line 45
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Core.Scripting.ScriptHost.RunTarget(String target) in C:\projects\cake\src\Cake.Core\Scripting\ScriptHost.cs:line 173
   at Submission#0.<get_Build>b__510_0(String target)
   at Submission#0.Builder.RunDotNetCore()
   at Submission#0.<<Initialize>>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.<RunSubmissionsAsync>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Scripting.Script`1.<RunSubmissionsAsync>d__21.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Cake.Scripting.Roslyn.RoslynScriptSessi
on.Execute(Script script) in C:\projects\cake\src\Cake\Scripting\Roslyn\RoslynScriptSession.cs:line 128
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments) in C:\projects\cake\src\Cake.Core\Scripting\
ScriptRunner.cs:line 212
   at Cake.Commands.BuildCommand.Execute(CakeOptions options) in C:\projects\cake\src\Cake\Commands\BuildCommand.cs:line 35
   at Cake.CakeApplication.Run(CakeOptions options) in C:\projects\cake\src\Cake\CakeApplication.cs:line 
45
   at Cake.Program.Main() in C:\projects\cake\src\Cake\Program.cs:line 74
---> (Inner Exception #0) Cake.Core.CakeException: OpenCover: Process returned an error (exit code 1).
   at Cake.Core.Tooling.Tool`1.ProcessExitCode(Int32 exitCode) in C:\projects\cake\src\Cake.Core\Tooling\Tool.cs:line 139
   at Cake.Core.Tooling.Tool`1.Run(TSettings settings, ProcessArgumentBuilder arguments, ProcessSettings processSettings, Action`1 postAction) in C:\projects\cake\src\Cake.Core\Tooling\Tool.cs:line 119
   at Cake.Common.Tools.OpenCover.OpenCoverRunner.Run(ICakeContext context, Action`1 action, FilePath outputPath, OpenCoverSettings settings) in C:\projects\cake\src\Cake.Common\Tools\OpenCover\OpenCoverRunner.cs:line 72
   at Cake.Common.Tools.OpenCover.OpenCoverAliases.OpenCover(ICakeContext context, Action`1 action, FilePath outputFile, OpenCoverSettings settings) in C:\projects\cake\src\Cake.Common\Tools\OpenCover\OpenCoverAliases.cs:line 66
   at Submission#0.OpenCover(Action`1 action, FilePath outputFile, OpenCoverSettings settings)
   at Submission#0.<<Initialize>>b__0_81()
   at Cake.Core.CakeTaskBuilderExtensions.<>c__DisplayClass8_0.<Does>b__0(ICakeContext x) in C:\projects\cake\src\Cake.Core\CakeTaskBuilderExtensions.cs:line 185
   at Cake.Core.ActionTask.<Execute>d__14.MoveNext() in C:\projects\cake\src\Cake.Core\ActionTask.cs:line 100
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Core.DefaultExecutionStrategy.<ExecuteAsync>d__4.MoveNext() in C:\projects\cake\src\Cake.Core\DefaultExecutionStrategy.cs:line 87
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Core.CakeEngine.<ExecuteTaskAsync>d__29.MoveNext() in C:\projects\cake\src\Cake.Core\CakeEngine.cs:line 266
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtim
e.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Core.CakeEngine.<RunTargetAsync>d__18.MoveNext() in C:\projects\cake\src\Cake.Core\CakeEngine.cs:line 164
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Scripting.BuildScriptHost.<RunTargetAsync>d__3.MoveNext() in C:\projects\cake\src\Cake\Scripting\BuildScriptHost.cs:line 45
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Cake.Core.Scripting.ScriptHost.RunTarget(String target) in C:\projects\cake\src\Cake.Core\Scripting\ScriptHost.cs:line 173
   at Submission#0.<get_Build>b__510_0(String target)
   at Submission#0.Builder.RunDotNetCore()
   at Submission#0.<<Initialize>>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.<RunSubmissionsAsync>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Scripting.Script`1.<RunSubmissionsAsync>d__21.MoveNext()<---
Command executed with exception: 


```

**Comment by AdmiringWorm** [comment]
Can you tell me how your `setup.cake`/`build.cake` looks like?
From the error message:
```
Cake.exe : The test source file "C:\projects\portal\test\Portal.Tests\bin\Any CPU\Release\netcoreapp2.0\Portal.Tests.dll" provided was not found.
```

it almost sounds like you're calling `Build.Run()` instead of `Build.RunDotNetCore()`.

**Comment by tjackadams** [comment]
Hi @AdmiringWorm 
my current setup.cake looks like this

```
#load nuget:https://www.myget.org/F/cake-contrib/api/v2?package=Cake.Recipe&prerelease

Environment.SetVariableNames();

BuildParameters.SetParameters(context: Context,
                            buildSystem: BuildSystem,
                            sourceDirectoryPath: "./src",
                            testDirectoryPath: "./test",
                            title: "Portal",
                            repositoryOwner: "CentralTechnology",
                            repositoryName: "portal",
                            shouldRunInspectCode: false,
                            nuGetSources: new []{
                                "https://api.nuget.org/v3/index.json",
                                "https://www.myget.org/F/cake-contrib/api/v3/index.json",
                                "https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json"
                            },
                            shouldExecuteGitLink: false,
                            isPublicRepository: false);



BuildParameters.PrintParameters(Context);

ToolSettings.SetToolSettings(context: Context,
                            dupFinderThrowExceptionOnFindingDuplicates: false,
                            dupFinderExcludePattern: new string[] { 
                                 BuildParameters.RootDirectoryPath + "/test/Portal.Tests//**/*.cs", 
                                 BuildParameters.RootDirectoryPath + "/src/Portal.Core/ConnectedServices//**/*.cs",
                                 BuildParameters.RootDirectoryPath + "/src/Portal.Core/Constants//**/*.cs",
                                 BuildParameters.RootDirectoryPath + "/src/Portal.Core/Common/Constants//**/*.cs",
                                 BuildParameters.RootDirectoryPath + "/src/Portal.Core//**/*BillingModel.cs",
                                 BuildParameters.RootDirectoryPath + "/src/Portal.EntityFrameworkCore/Migrations//**/*.cs" },
                            testCoverageFilter: "+[*]* -[xunit.*]* -[*.Tests]* -[SharpRaven]*",
                            testCoverageExcludeByAttribute: "*.ExcludeFromCodeCoverage*",
                            testCoverageExcludeByFile: "*/*Designer.cs;*/*.g.cs;*/*.g.i.cs"
                            );



Build.RunDotNetCore();
```

**Comment by AdmiringWorm** [comment]
I see, in that case I actually don't know.
Think we'll need the help of @gep13 on this one.

**Comment by gep13** [comment]
@tjackadams is this on a public project? What AppVeyor Build Image are you using?

**Comment by tjackadams** [comment]
@gep13 it's a private project and i'm using the Visual Studio 2017 image on AppVeyor

**Comment by tjackadams** [comment]
Ok i managed to resolve this, so i think this can be closed now although i don't really know what the solution was.
The problem seemed to be in my test project .csproj file, which i found out by creating a new test project with some successful asserts and seeing if that found the correct path.

Here is the .csproj before
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <AssetTargetFallback>$(AssetTargetFallback);portable-net45+win8+wp8+wpa81;</AssetTargetFallback>
    <AssemblyName>Portal.Tests</AssemblyName>
    <PackageId>Portal.Tests</PackageId>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Webroot\**" />
    <EmbeddedResource Remove="Webroot\**" />
    <None Remove="Webroot\**" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\..\src\SolutionInfo.cs" Link="Properties\SolutionInfo.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Portal.Application\Portal.Application.csproj" />
    <ProjectReference Include="..\..\src\Portal.Core\Portal.Core.csproj" />
    <ProjectReference Include="..\..\src\Portal.EntityFrameworkCore\Portal.EntityFrameworkCore.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AutoFixture" Version="4.0.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.5.0" />
    <PackageReference Include="Moq" Version="4.8.1" />
    <PackageReference Include="NSubstitute" Version="3.1.0" />
    <PackageReference Include="Shouldly" Version="3.0.0" />
    <PackageReference Include="xunit" Version="2.3.1" />
    <PackageReference Include="xunit.extensibility.execution" Version="2.3.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.3.1" />
    <PackageReference Include="Abp.TestBase" Version="3.4.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="2.0.1" />
    <PackageReference Include="Castle.Core" Version="4.2.1" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'net461' ">
    <Reference Include="System" />
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Microsoft.AspNetCore.Hosting">
      <HintPath>..\..\..\..\..\..\..\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.hosting\2.0.1\lib\netstandard2.0\Microsoft.AspNetCore.Hosting.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Service Include="{82a7f48d-3b50-4b1e-b82e-3ada8210c358}" />
  </ItemGroup>
</Project>
```

Here it is after

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\..\src\SolutionInfo.cs" Link="Properties\SolutionInfo.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Portal.Application\Portal.Application.csproj" />
    <ProjectReference Include="..\..\src\Portal.Core\Portal.Core.csproj" />
    <ProjectReference Include="..\..\src\Portal.EntityFrameworkCore\Portal.EntityFrameworkCore.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AutoFixture" Version="4.0.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.5.0" />
    <PackageReference Include="Moq" Version="4.8.1" />
    <PackageReference Include="NSubstitute" Version="3.1.0" />
    <PackageReference Include="Shouldly" Version="3.0.0" />
    <PackageReference Include="xunit" Version="2.3.1" />
    <PackageReference Include="xunit.core" Version="2.3.1" />  
    <PackageReference Include="xunit.extensibility.execution" Version="2.3.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.3.1" />
    <PackageReference Include="Abp.TestBase" Version="3.4.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="2.0.1" />
    <PackageReference Include="Castle.Core" Version="4.2.1" />
    <DotNetCliToolReference Include="dotnet-xunit" Version="2.3.1" />
  </ItemGroup>
  <ItemGroup>
    <Service Include="{82a7f48d-3b50-4b1e-b82e-3ada8210c358}" />
  </ItemGroup>
</Project>
```

just thought i would post the comparison incase anyone has a similar issue, they can see the bits i removed from the .csproj.
