### ISSUE TITLE
Add possibility to generate documentation on source-changes

### ISSUE THREAD

**Issue by nils-a** [cake-contrib/Cake.Recipe#615]
currently `Publish-Documentation` checks for changes to documentation files in the current commit: 
https://github.com/cake-contrib/Cake.Recipe/blob/1.1.2/Cake.Recipe/Content/wyam.cake#L33-L46

It would be nice to have the ability to check for source-file changes, too. Probably add a new BuildParameter `ShouldGenerateDocumentationOnSrcChange` ?

One would have to include the `sourceDirectoryPath` and possibly exclude the `testDirectoryPath`.

**Comment by nils-a** [comment]
Never mind. Should be possible, when https://github.com/cake-contrib/Cake.Recipe/commit/a042e8a8b0882eb34c64f5a8dcc519f744ce333a is released

**Comment by gep13** [comment]
@nils-a I think we should open this again, just to make sure that it works as intended, once things have shipped.  That way, it won't drop off the radar.

**Comment by nils-a** [comment]
@gep13 agreed. From looking at the diffs again I'm no longer sure whether the changes do what I suspected them to do at first glance or rather whether they enable/disable generation of source documentation at all.

**Comment by nils-a** [comment]
I'm guessing something like https://github.com/cake-contrib/Cake.Recipe/compare/develop...nils-a:feature/GH-615 is needed. 

However, I can not get the current develop-branch of cake.recipe to work (i.e. not even the integration tests) so I'm not sure "what" the code does... (Hence, no PR at the moment...)

**Comment by gep13** [comment]
@nils-a what issues are you seeing?  If you can provide some more information we should hopefully be able to help.

**Comment by nils-a** [comment]
@gep13 on a vanilla clone, running `.\build.ps1 ; .\build.ps1 -Script test.cake` the error is

```
========================================
Tests: Cake.Twitter
========================================
Testing c:/CakeRecipeTests/repos/Cake.Twitter/recipe.cake...
Could not load c:\CakeRecipeTests\repos\Cake.Twitter\tools\Addins\Cake.Issues.Reporting.Generic.0.9.0-beta0001\lib\netstandard2.0\Microsoft.CodeAnalysis.Scripting.dll (missing System.Runtime.Loader, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
Using Local Build Provider...
Testing to see if valid git repository...
Unable to find git, setting default values for repository properties...
Printing Build Parameters...
IsLocalBuild: True
IsPullRequest: False
IsMainRepository: False
IsPublicRepository: True
IsTagged: False
BranchType: Unknown
TreatWarningsAsErrors: True
ShouldPublishToMyGetWithApiKey: True
ShouldSendEmail: True
ShouldPostToGitter: True
ShouldPostToSlack: True
ShouldPostToTwitter: True
ShouldPostToMicrosoftTeams: False
ShouldDownloadFullReleaseNotes: False
ShouldDownloadMilestoneReleaseNotes: False
ShouldNotifyBetaReleases: False
ShouldDeleteCachedFiles: False
ShouldGenerateDocumentation: False
ShouldDocumentSourceFiles: False
ShouldRunIntegrationTests: False
ShouldCalculateVersion: True
BuildAgentOperatingSystem: Windows
IsRunningOnAppVeyor: False
RepositoryOwner: cake-contrib
RepositoryName: Cake.Twitter
TransifexEnabled: False
CanPullTranslations: False
CanPushTranslations: False
PrepareLocalRelease: False
BuildAgentOperatingSystem: Windows
ForceContinuousIntegration: False
PreferredBuildAgentOperatingSystem: Windows
PreferredBuildProviderType: AppVeyor
WyamRootDirectoryPath: c:/CakeRecipeTests/repos/Cake.Twitter/docs
WyamPublishDirectoryPath: c:/CakeRecipeTests/repos/Cake.Twitter/BuildArtifacts/temp/_PublishedDocumentation
WyamConfigurationFile: c:/CakeRecipeTests/repos/Cake.Twitter/config.wyam
WyamRecipe: Docs
WyamTheme: Samson
WyamSourceFiles: ../../Source/**/{!bin,!obj,!packages,!*.Tests,}/**/*.cs
Wyam Deploy Branch: [NULL]
Wyam Deploy Remote: [NULL]
WebHost: cake-contrib.github.io
WebLinkRoot: Cake.Twitter
WebBaseEditUrl: https://github.com/cake-contrib/Cake.Twitter/tree/develop/docs/input/
NuSpecFilePath: c:/CakeRecipeTests/repos/Cake.Twitter/Cake.Recipe/Cake.Recipe.nuspec
NugetConfig: c:/CakeRecipeTests/repos/Cake.Twitter/NuGet.Config (False)
NuGetSources: https://api.nuget.org/v3/index.json, https://www.myget.org/F/cake-contrib/api/v3/index.json
RestorePackagesDirectory: [NULL]
EmailRecipient: [NULL]
EmailSenderName: [NULL]
EmailSenderAddress: [NULL]
Setting up tools...

----------------------------------------
Setup
----------------------------------------
Initializing Cake.Issues.Recipe (Version 0.4.0-beta0001)...

----------------------------------------
Setup
----------------------------------------
Error: Could not find an installer for the 'dotnet' scheme.

----------------------------------------
Teardown
----------------------------------------
An error occurred in a custom teardown action.
Teardown error: System.InvalidOperationException: The context data has not been setup.
   at Cake.Core.CakeDataService.Get[TData]()
   at Cake.Core.CakeEngineActions.<>c__DisplayClass21_0`1.<RegisterTeardown>b__0(ITeardownContext context)
   at Cake.Core.DefaultExecutionStrategy.PerformTeardown(Action`1 action, ITeardownContext teardownContext)
   at Cake.Core.CakeEngine.PerformTeardown(IExecutionStrategy strategy, ICakeContext context, Stopwatch stopWatch, CakeReport report, Boolean exceptionWasThrown, Exception thrownException)
Error: One or more errors occurred.
        Cake: Process returned an error (exit code 1).
Cake.Twitter: Cake.Core.CakeException: Cake: Process returned an error (exit code 1).
   at Cake.Core.Tooling.Tool`1.ProcessExitCode(Int32 exitCode)
   at Cake.Core.Tooling.Tool`1.Run(TSettings settings, ProcessArgumentBuilder arguments, ProcessSettings processSettings, Action`1 postAction)
   at Cake.Common.Tools.Cake.CakeRunner.ExecuteScript(FilePath scriptPath, CakeSettings settings)
   at Submission#0.<>c__DisplayClass0_1.<<Initialize>>b__8(ICakeContext context) in D:\_dev\Cake.Recipe\test.cake:line 125

========================================
Tests
========================================
An error occurred when executing task 'Tests'.

----------------------------------------
Teardown
----------------------------------------
Error: One or more errors occurred.
        https://github.com/cake-contrib/Cake.Gulp.git
        https://github.com/cake-contrib/Cake.Http.git
        https://github.com/cake-contrib/Cake.Twitter.git
```

and while I'm guessing the error originates at https://github.com/cake-build/cake/blob/3e8bd7a7589d0e38e819011230aff215f8eef4ce/src/Cake.Core/Scripting/ScriptProcessor.cs#L104 I'm currently somewhat lost in tracking it down.

**Comment by gep13** [comment]
Ah, so the build itself works, but the included integration tests don't.  I "think" that actually makes sense.  Those projects won't have been updated to include the Cake.Recipe 2.0 related changes, and likely other things, so I don't think that this is a showstopper.  @AdmiringWorm has another repository that we have been using for testing out the changes to Cake.Recipe (https://github.com/cake-contrib/Cake.Recipe.Tests).  For now, I wouldn't worry about running the local integration tests, but we will need to get these fixed up.

**Comment by nils-a** [comment]
@gep13 Thanks for the pointer - I wasn't even sure my code worked in the slightest (and it didn't..). So I needed some tests :-)
